### ISSUE TITLE
make install does not work on windows

### ISSUE THREAD

**Issue by josephroffey** [carlnordenfelt/aws-api-gateway-for-cloudformation#1]
shell script uses rm which is not available in windows, suggest using node.js instead

**Comment by BryanCrotaz** [comment]
cannot use under cygwin as npm doesn't work on cygwin

**Comment by carlnordenfelt** [comment]
Fair point. I'll rewrite the installation scripts in nodejs instead. It'll take a few weeks though as I currently have no access to my computer. If you create a pull request with new scripts I'd be happy to merge them when I get back to the real world :)

**Comment by carlnordenfelt** [comment]
The installation scripts have been rewritten. Please give me feedback on the new ones, they will hopefully work better.

**Comment by carlnordenfelt** [comment]
I'll close this. Please open a new issue if the problems remain
