### ISSUE TITLE
404 in installation link from Readme

### ISSUE THREAD

**Issue by tavisrudd** [carlnordenfelt/aws-api-gateway-for-cloudformation#16]
```
curl -IL http://apigatewaycloudformation.s3-website-eu-west-1.amazonaws.com/install/latest
HTTP/1.1 301 Moved Permanently
x-amz-id-2: 7fidhphlGddzwjtSDmoUWpDHkXE+MYUPaRwgxeZAp6kRt+TXNEhj5w8NfjPcXNR03ygoe3IwFno=
x-amz-request-id: AC2A7810742CC38E
Date: Fri, 26 Feb 2016 15:19:28 GMT
Location: /install/v.zip
Content-Length: 0
Server: AmazonS3

HTTP/1.1 404 Not Found
x-amz-error-code: NoSuchKey
x-amz-error-message: The specified key does not exist.
x-amz-error-detail-Key: install/v.zip
x-amz-request-id: 3474FD3AE480C355
x-amz-id-2: Kr2aDePPulMN8I3DBfXK/CUArFSHZIzxxK1KANvEaFxwTF44uQ2NJDP8ybYIUE0wsK+S8CcQbfU=
Transfer-Encoding: chunked
Date: Fri, 26 Feb 2016 15:19:27 GMT
Server: AmazonS3
```

**Comment by carlnordenfelt** [comment]
Looks like an issue with the publish script. I'll get on it as soon as possible. In the meantime you can specify the version manually

**Comment by carlnordenfelt** [comment]
Links fixed with a workaround. I'll look at the script when Im not on the go :)

thanks for notifying me!

**Comment by tavisrudd** [comment]
Thanks. I ran into issues when specifying v1.1.4 manually as well. After 
running unix/install.sh and unix/deploy.sh, I attempted to create a 
stack from Test.template, it got stuck and I found this in the 
cloudwatch logs for the main lambda:
  ```
Unable to import module 'lib/index':
Error at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
```

**Comment by carlnordenfelt** [comment]
Are you still having that issue after my first fix? If so I'll have to dig in to that. My first thought is that there is something off in the packaging script.

**Comment by carlnordenfelt** [comment]
There was an issue in the publish script, I've rectified that.

I installed v.1.1.4.zip both by specifying the version manually and by simply going with the latest version and both works fine.
Are you still having issues?

**Comment by tavisrudd** [comment]
Sorry, I haven't had a chance to try it again since. I'll give it a shot today.

**Comment by carlnordenfelt** [comment]
As of version 1.2.0 the update procedure has changed so this should no longer be a problem.
