### ISSUE TITLE
renaming resource key results in error

### ISSUE THREAD

**Issue by BryanCrotaz** [carlnordenfelt/aws-api-gateway-for-cloudformation#18]
When renaming a variable path part the new one gets added before the old one is deleted

e.g.
/resource1/{key}
renamed to 
/resource1/{key1}

BadRequestException: Resource with id 'null' has more than one variable component as a direct child: [{key}, {key1}]

**Comment by carlnordenfelt** [comment]
I'll have to look at that. Can you send me a template example?

**Comment by carlnordenfelt** [comment]
I just had a quick look, are you updating a Resource or a Method?

When resources are updated I call updateResource. If there is an issue there you've stumbled across a bug in API Gateway.
When methods are updated, the old method is deleted and a new method is created in its place. If there is a problem here, I guess again we've come across an interesting "feature" in API Gateway.

This is fairly interesting too:
> aws apigateway update-resource --rest-api-id abc123 --resource-id abc456 --patch-operations op=replace,path=/pathPart,value="{test1}

Error parsing parameter '--patch-operations': Expected: ',', received: '}' for input:
op=replace,path=/pathPart,value={test1}
                                           ^
> aws apigateway update-resource --rest-api-id abc123 --resource-id abc456 --patch-operations op=replace,path=/pathPart,value="test2"
{
    "path": "/test/test2", 
    "pathPart": "test2", 
    "id": "abc456", 
    "parentId": "abc456789"
}

**Comment by BryanCrotaz** [comment]
Interesting!

**Comment by BryanCrotaz** [comment]
> I just had a quick look, are you updating a Resource or a Method?

A resource

> e.g.
> /resource1/{key}
> renamed to 
> /resource1/{key1}

**Comment by carlnordenfelt** [comment]
Can we close this as an AWS bug or do you have more information for me?

**Comment by carlnordenfelt** [comment]
Ok to close?
