### ISSUE TITLE
make install fails on linux

### ISSUE THREAD

**Issue by josephroffey** [carlnordenfelt/aws-api-gateway-for-cloudformation#2]
make install fails with npm-debug log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'setup' ]
2 info using npm@3.5.2
3 info using node@v5.4.0
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info lifecycle AWS-APIGateway-for-CloudFormation@0.0.1~presetup: AWS-APIGateway-for-CloudFormation@0.0.1
6 silly lifecycle AWS-APIGateway-for-CloudFormation@0.0.1~presetup: no script for presetup, continuing
7 info lifecycle AWS-APIGateway-for-CloudFormation@0.0.1~setup: AWS-APIGateway-for-CloudFormation@0.0.1
8 verbose lifecycle AWS-APIGateway-for-CloudFormation@0.0.1~setup: unsafe-perm in lifecycle true
9 verbose lifecycle AWS-APIGateway-for-CloudFormation@0.0.1~setup: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/martyn/aws-api-gateway-for-cloudformation/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle AWS-APIGateway-for-CloudFormation@0.0.1~setup: CWD: /home/martyn/aws-api-gateway-for-cloudformation
11 silly lifecycle AWS-APIGateway-for-CloudFormation@0.0.1~setup: Args: [ '-c', './_scripts/install.sh' ]
12 info lifecycle AWS-APIGateway-for-CloudFormation@0.0.1~setup: Failed to exec setup script
13 verbose stack Error: AWS-APIGateway-for-CloudFormation@0.0.1 setup: `./_scripts/install.sh`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:87:13)
13 verbose stack     at ChildProcess.emit (events.js:172:7)
13 verbose stack     at maybeClose (internal/child_process.js:821:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid AWS-APIGateway-for-CloudFormation@0.0.1
15 verbose cwd /home/martyn/aws-api-gateway-for-cloudformation
16 error Linux 3.13.0-63-generic
17 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "setup"
18 error node v5.4.0
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error AWS-APIGateway-for-CloudFormation@0.0.1 setup: `./_scripts/install.sh`
24 error spawn ENOENT
25 error Failed at the AWS-APIGateway-for-CloudFormation@0.0.1 setup script './_scripts/install.sh'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the AWS-APIGateway-for-CloudFormation package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     ./_scripts/install.sh
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs AWS-APIGateway-for-CloudFormation
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls AWS-APIGateway-for-CloudFormation
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]

**Comment by carlnordenfelt** [comment]
Interesting, it looks like it doesn't find the install script. I've only tested it on Mac but assumed it would work on Linux out of the box. Would it be possible for you to see if you can address the issue with a pull request and I'll merge it as soon as possible (in about 4 weeks).

**Comment by carlnordenfelt** [comment]
The installation scripts have been rewritten. Please give me feedback on the new ones, they will hopefully work better.

**Comment by carlnordenfelt** [comment]
I will close this. Open a new issue if there are more problems with this.
