### ISSUE TITLE
no build script so can't build a fork to try it out

### ISSUE THREAD

**Issue by BryanCrotaz** [carlnordenfelt/aws-api-gateway-for-cloudformation#29]

**Comment by carlnordenfelt** [comment]
You can run the package script (unix) and upload the source file manually.
_scripts/publish.sh -a package

The previous deploy scripts were removed in favor of CloudFormation installation.
If you need a package script for windows I'd be great if you could create a pull request with just that.
Or simply zip the source package straight up, that's all you need.

**Comment by carlnordenfelt** [comment]
I've added a comment at the end of the readme with instructions for how to manually upload and test.

**Comment by BryanCrotaz** [comment]
:)

On 28 March 2016 at 11:58, Carl Nordenfelt <notifications@github.com> wrote:

> I've added a comment at the end of the readme with instructions for how to
> manually upload and test.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/carlnordenfelt/aws-api-gateway-for-cloudformation/issues/29#issuecomment-202340568>
>



-- 
Bryan Crotaz
Managing Director
Silver Curve
