### ISSUE TITLE
Errors during create of stack: NoSuchBucket

### ISSUE THREAD

**Issue by alshamma** [carlnordenfelt/aws-api-gateway-for-cloudformation#31]
Two problems. I chose the latest us-west-1 template. Tried Create. Got this output:

**14:59:29 UTC-0700	CREATE_FAILED	AWS::Lambda::Function	LambdaFunction	Error occurred while GetObject. S3 Error Code: NoSuchBucket. S3 Error Message: The specified bucket does not exist
**14:59:28 UTC-0700	CREATE_IN_PROGRESS	AWS::Lambda::Function	LambdaFunction	

I fixed this problem by switching to the correct region in CloudFormation. 

Second time, I got this output:
	15:08:08 UTC-0700	CREATE_FAILED	AWS::Lambda::Function	LambdaFunction	Resource is not supported in this region

As Lambdas are not supported in us-west-1, but they are in us-west-2, shouldn't the template be for us-west-2?

**Comment by carlnordenfelt** [comment]
Hi,

Problem one is hard to address.
You are absolutely right about us-west-2 though. I will fix this asap, give
me an hour or two.

**Comment by carlnordenfelt** [comment]
Fixed as of 1.3.2

**Comment by alshamma** [comment]
Just want to let you know your fix worked for me. Thanks!

**Comment by carlnordenfelt** [comment]
I'm glad it did and thanks for the feedback!
