### ISSUE TITLE
runtime error when using IAM certificate

### ISSUE THREAD

**Issue by deno085** [carlnordenfelt/aws-api-gateway-for-cloudformation#35]
I'm creating an API using an IAM server certificate and the lambda function is throwing the following runtime error (from CloudWatch):

2016-03-30T21:27:20.511Z	2f0f9e85-f6be-11e5-a5ea-ef9a61e1e76a	TypeError: Cannot call method 'replace' of undefined at Object.pub.parseCertificate (/var/task/lib/service/util/certificateParser.js:21:10) at Response.<anonymous> (/var/task/lib/service/ApiDomainName/ApiDomainNameService.js:37:61) at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:354:18) at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20) at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:77:10) at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:596:14) at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:21:10) at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12) at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10 at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:37:9)

I'm guessing it's having trouble finding the cert, but here's what I have going into that:
```javascript
    "ApiDomainName" : {
        "Type" : "Custom::ApiDomainName",
        "Properties" : {
            "ServiceToken": { "Ref": "ServiceFunctionARN"},
            "domainName": { "Fn::Join": ["", [ { "Ref": "EnvName"},"-api.example.com" ] ] },
            "certificateName": "wildcardNamecheap",
            "iamServerCertificateName": "wildcardNamecheap",
            "certificatePrivateKey" : { "Ref": "sslCertPrivateKey" }
        }
    },
```

and the lambda event:
```javascript
{
    "RequestType": "Create",
    "ServiceToken": "arn:aws:lambda:us-west-2:512730486721:function:APIGatewaySupport-LambdaFunction-1C915UXOQUBJ",
    "ResponseURL": "https://cloudformation-custom-resource-response-uswest2.s3-us-west-2.amazonaws.com/arn%3Aaws%3Acloudformation%3Aus-west-2%XXX%3Astack/app-12/2c500910-f6be-11e5-80fa-503f2a2cee4a%7CApiDomainName%7C05f07a27-3bbd-4737-bb78-1cf1379233e2?AWSAccessKeyId=XXX&Expires=1459380439&Signature=prp3TeQ0S%2F5EM4MCJ3fnr3nmVm4%3D",
    "StackId": "arn:aws:cloudformation:us-west-2:XXX:stack/app-12/2c500910-f6be-11e5-80fa-503f2a2cee4a",
    "RequestId": "05f07a27-3bbd-4737-bb78-1cf1379233e2",
    "LogicalResourceId": "ApiDomainName",
    "ResourceType": "Custom::ApiDomainName",
    "ResourceProperties": {
        "ServiceToken": "arn:aws:lambda:us-west-2:XXX:function:APIGatewaySupport-LambdaFunction-1C915UXOQUBJ",
        "certificatePrivateKey": "***masked***",
        "certificateName": "wildcardNamecheap",
        "domainName": "app-12-api.example.com",
        "iamServerCertificateName": "wildcardNamecheap"
    }
}
```

The end result is the stack create just hangs..

**Comment by carlnordenfelt** [comment]
Hi,
Can you provide more logs from the Lambda or was that it?
From the looks of it it doesn't get the certificate chain which is strange.

Can you try running the follow cli command and paste the response (mask any sensitive details).

    aws iam get-server-certificate --server-certificate-name wildcardNamecheap

**Comment by carlnordenfelt** [comment]
I see that the chain is actually optional when uploading a server certificate to IAM.
It is however required when uploading it to API Gateway so in this case, if the chain is not available, creation should fail.

**Comment by carlnordenfelt** [comment]
If you upgrade to version 1.4.2 and re-run the lambda event manually your stack creation should fail gracefully. My best guess is that your certificate does not have a Certificate Chain and this is required when uploading to API Gateway so I have added a check that ensures that body the body and the chain are set and fails if they're not.

Try it out and let me know how it works.

**Comment by deno085** [comment]
It does appear you are correct.  I created a new IAM cert with the chain, and it it works with 1.4.1.  I tried my old cert (without the chain) with 1.4.2 and it did fail as expected

**Comment by carlnordenfelt** [comment]
Great! Thanks for confirming and for testing both cases :)
