### ISSUE TITLE
So, how do I actually use this to deploy my api?

### ISSUE THREAD

**Issue by kmamykin** [carlnordenfelt/aws-api-gateway-for-cloudformation#36]
Ok I read the readme twice, but I still do not get what are the actual steps to create a CF description of my API and deploy it. The templates in the Change Log (as described in the Install section) deploy the actual Lambda function, but where do describe the api? 

May be an example API project using aws-api-gateway-for-cloudformation ? Would love to see that.

**Comment by carlnordenfelt** [comment]
Hi!

The templates in the change log only install the Lambda function that enables you to use everything the readme describes. If you could describe what steps you have executed and more precisely describe what you are having trouble with I'll try to help you as best as I can.
Perhaps the provided Test template can give you some guidande?
https://github.com/carlnordenfelt/aws-api-gateway-for-cloudformation/blob/master/Test.template

Any feedback on the documentation is welcome as i myself am struggling with how to write it :)

/ Carl

**Comment by kmamykin** [comment]
I think I was lacking the big picture how CF and custom resources work. I did not realize that the Install instructions install *your* lambda function on *my* account from already existing code in *your* bucket. After which my own CF template with custom resources would create API gateway resources.

After reading http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-custom-resources.html it make sense (may be worth including the link in the overview), as well as the "big picture" 

Thanks for working on this!

**Comment by carlnordenfelt** [comment]
I appreciate the feedback.
I'll give the installation documentation some thought and try to clarify this. 
I'll leave this issue open until I've adjusted the documentation accordingly.

Thanks again

**Comment by carlnordenfelt** [comment]
I have updated the documentation, hopefully it explains these things a bit better now.
