### ISSUE TITLE
Error on creating Custom::ApiMethod: "Response object is too long."

### ISSUE THREAD

**Issue by pit** [carlnordenfelt/aws-api-gateway-for-cloudformation#37]
Hello!

I'm using your tool to create API.
When cloudformation creating resource Custom::ApiMethod I'm getting following error:

CREATE_FAILED	Custom::ApiMethod	SearchJobsMethod	Response object is too long.

Do you have any limitations for integration response template?

**Comment by carlnordenfelt** [comment]
Hi!

Can you provide the full logs clod watch?
I think this might be a limitation in apologize gateway but I'd like to see
the logs before I say that for sure.

Thanks

**Comment by pit** [comment]
I'll repeat error under clean account and provide you logs. Will come back in two days.

**Comment by pit** [comment]
It looks like it was some AWS issues or bug in AWS API.
I've tried several times to create or update API via cloudformation - now everything works

**Comment by carlnordenfelt** [comment]
Hi,

I've got good news and bad news :)
I can reproduce this issue but I also know the cause.

When creating a method with a lot of response codes it grows quite a bit and the entire method definition is shipped in the CustomResource response.
CustomResources have a 4K limit on the response size and I just created a method with a 36K response (!) which breaks just like you describe.

I will push a fix which will strip the ApiMethod resource response a bit by simply removing data that I deem uninteresting from it.

**Comment by carlnordenfelt** [comment]
Version 1.5.1 adresses this issue by stripping away 
methodResponses, methodIntegration.integrationResponses, methodIntegration.requestTemplates and requestModels from the ApiMethod response.

**Comment by lakshmantgld** [comment]
I am having the same issue now. **Response object is too long**. I use customeResources and I send certificates as response, which am sure is greater than 4k. Any solution for this. I have to send those certificates as response which will be needed as input by another logical resource in cloudFromation. :(

**Comment by carlnordenfelt** [comment]
Hi,

To provide any insight at all I'll need the logs from cloud watch.

I'm also not sure what you mean when you say that you send the certificate
in the response and how that relates to cloudformation and the custom
resource?
What does your template look like?

**Comment by lakshmantgld** [comment]
I mean the response that I send from customResource i.e Lambda is large(greater than 4k). The response I send is the contents of the certificate(.pem key). I know the 4k is the limit. So, the obvious solution to this problem is to use another bucket and store the response. I am asking if there is any other better approach if I have to send a response of more than 4k from customResource.

**Comment by carlnordenfelt** [comment]
What version are you running? Version 1.5.1 addressed the issue with big method definitions breaking.
