### ISSUE TITLE
Using Swagger/OpenAPI definitions

### ISSUE THREAD

**Issue by wjordan** [carlnordenfelt/aws-api-gateway-for-cloudformation#38]
Now that API Gateway supports importing Swagger/OpenAPI definitions directly (see [documentation](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html)), would it be possible to support the import API method in this custom CloudFormation resource? This would make the need to maintain all intermediate resources obsolete, if it would be possible to just add a Swagger definition to a CloudFormation property directly.

**Comment by carlnordenfelt** [comment]
I will definitely look into this and perhaps offer it as an alternative way
to write your API definitions.

**Comment by carlnordenfelt** [comment]
Added in version 1.5.0 with a couple of caveats. Check it out here: https://apigatewaycloudformation.bynordenfelt.com/#custom-ApiImport
