### ISSUE TITLE
CORS on root resource

### ISSUE THREAD

**Issue by rnhurt** [carlnordenfelt/aws-api-gateway-for-cloudformation#40]
I'm trying to add CORS support to the root "/" resource.  However, the ApiResource requires a pathPart but doesn't accept a null "" or root "/" string.  Is there a way to create CORS options without specifying a pathPart or is there a magic "null" pathPart that will create things at the root resource?

**Comment by carlnordenfelt** [comment]
Hi, the Root resource is already created by API gateway, I'm honestly not
sure it it's possible to manipulate but it would require a separate
resource type to do so.
What you can do is create a regular http method of type OPTIONS on the root
resource but then you have to make sure you add the allow-origin header on
the other methods on the root resource. Tedious....

I'll give this some thought and see what I come up with, enabling Cora on
the root resource makes perfect sense so it sh be supported :)

**Comment by rnhurt** [comment]
Yes, that makes sense.  I think creating the OPTIONS method on root might work.  I'll give it a shot.  :)

**Comment by carlnordenfelt** [comment]
From version 1.6.0 you can specify CORS config on the rest api, this config will be applied to the parent resource of the API. It works exactly the same way as CORS configuration on Custom::APIResource.
https://apigatewaycloudformation.bynordenfelt.com/#custom-RestApi
