### ISSUE TITLE
Complex api deployment fails due to api gateway throttling

### ISSUE THREAD

**Issue by BryanCrotaz** [carlnordenfelt/aws-api-gateway-for-cloudformation#41]
Increase retry count and intervals to fix

**Comment by carlnordenfelt** [comment]
I'll merge your pull request but I'm uncertain about version. The increase
gives a potential execution time of 32*5 seconds plus change which is way
more than the default installation setting at 30 seconds meaning that this
is a potentially breaking change for a fix. Suggestions?

**Comment by BryanCrotaz** [comment]
Whop a documentation change in.

If you see your lambda timing out, increase the maximum run time to 3
minutes on the lambda settings in the AWS UI.

**Comment by carlnordenfelt** [comment]
I bumped to 1.7.0 and added Upgrade Notes in the change log. Also set the default to 180 seconds
