### ISSUE TITLE
May I ask why use "Custom::RestApi"?

### ISSUE THREAD

**Issue by justabuzz** [carlnordenfelt/aws-api-gateway-for-cloudformation#46]
Hi,

Considering that the CloudFormation API supports [RestApi](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html), [Deployment](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-deployment.html) and [Stage](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-stage.html) and all the other native APIG resources, then why are you using Custom::RestApi? Is there something that the current CF APIG resources lack which can be achieved only by using the Custom option?

I wrote a [sample project](https://github.com/justabuzz/serverless-landing-page) where I managed to allocate all API Gateway resources using the official and documented CF APIs.

I'm curious to know whether Custom resources fill in a gap I'm not aware of? One thing I did notice was that you can't get the Endpoint of an AWS::ApiGateway::Stage, which I think is quite a basic requirement. Is there anything else?

Thanks!

**Comment by carlnordenfelt** [comment]
Hi,

This project was started before CloudFormation launched its native API Gateway support.
Now that CloudFormation supports most resources it comes down to a matter of taste.

The CloudFormation support is more or less mapping the SDK APIs one to one which means that the configuration is quite complex and there is a lot of duplication while this project aims to simplify things. One example is CORS configuration and API Method responses but there are several other simplifications to how you express and configure your APIs using these custom resources.

I would still advice anyone who wants to create a setup from scratch to first look at the native resources and see if they are enough before looking at this project. Installing and using this project comes with its own limitations as it has to be maintained to keep up with new releases from API Gateway. Of course, the native resource must also be maintained but they are provided by Amazon and _should_ come with more assurance that they always work as intended. 
This project is tested throughly but as the License states, there are no guarantees.

I hope this clarifies my reasoning and why I'm keeping this project alive. Let me know if you have more questions :)

/ Carl

**Comment by justabuzz** [comment]
Hi @carlnordenfelt, thanks for the detailed reply. Appreciate that. It was more of a sanity check for me and it aligns with what I thought :)
