### ISSUE TITLE
Export ServiceToken for cross-stack references

### ISSUE THREAD

**Issue by jancona** [carlnordenfelt/aws-api-gateway-for-cloudformation#51]
Now that CF has [cross-stack references](https://aws.amazon.com/blogs/aws/aws-cloudformation-update-yaml-cross-stack-references-simplified-substitution/), would it make sense to export the Lambda ARN so that stacks can retrieve it using ImportValue?

Note that the exported names are global to the account and region, so you might want to qualify it with the stack name of the creating stack, e.g. `{StackName}:APIGatewayCloudFormation:ServiceToken`

Or perhaps there's another simple way to do this that I'm not aware of.

**Comment by carlnordenfelt** [comment]
That's not a bad idea since it would be a backwards compatible change unlike naming the function.

**Comment by svozza** [comment]
I'd really like this functionality, would you accept a PR?

**Comment by carlnordenfelt** [comment]
Sure!

**Comment by svozza** [comment]
Great! Do you mind if I convert the template to yaml?

**Comment by carlnordenfelt** [comment]
I would prefer if you didn't do that :)

**Comment by svozza** [comment]
No probs, that's why I thought I'd ask first!
