### ISSUE TITLE
Given our PRs we think the dynamo table can now be removed

### ISSUE THREAD

**Issue by BryanCrotaz** [carlnordenfelt/aws-api-gateway-for-cloudformation#6]

**Comment by carlnordenfelt** [comment]
I'll look at when I'm back. For compatibility reasons it's a bit tricky to remove it although new installations should not use it. One could also create a branch with the tables intact.  Something to consider.

**Comment by BryanCrotaz** [comment]
Use semver to show it's not backward compatible. Given how new the
repo is and the bugs that were there I doubt anyone other than you or
us is using it, or you'd have seen bug reports here. So sooner the
better!

**Comment by carlnordenfelt** [comment]
Closed after merging PR #4
