### ISSUE TITLE
lambda-arn mismatch

### ISSUE THREAD

**Issue by Trii** [carlnordenfelt/aws-api-gateway-for-cloudformation#7]
Sometimes you use `./_scripts/lambda-arn` and sometimes you use `./lambda-arn`. `./_scripts/install.sh` writes to the latter yet other scripts look for the former. This causes it to fail on OS X and probably linux

**Comment by carlnordenfelt** [comment]
I'm in the process of completely re-writing the installation scripts. This should be done pretty soon, mostly testing left to do.

**Comment by Trii** [comment]
I'll close the PR then. Thanks!
